export const customersList = [
  {
    id: 1,
    name: "Namanya panjang banget ini heey",
    address: "ini addressnya juga panjang banget tolong lahh heeyyy bisa yuk bisa",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: true,
  },
  {
    id: 2,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: true,
  },
  {
    id: 3,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 4,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: true,
  },
  {
    id: 5,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 6,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 7,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 8,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 9,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
  {
    id: 10,
    name: "test",
    address: "test address",
    country: "test country",
    phone_number: "tes",
    job_title: "test test",
    status: false,
  },
];
